version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3.13.0-management # https://hub.docker.com/_/rabbitmq
    restart: 'no'
    container_name: rabbitmq
    ports:
      - '5672:5672' # listeners.tcp.default
      - '15672:15672' # management.listener.port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ./conf/rabbitmq.conf:/etc/rabbitmq/conf.d/rabbitmq.conf:ro
      - ./conf/definitions.json:/etc/rabbitmq/conf.d/definitions.json:ro